# Generated by Django 3.0.7 on 2020-06-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'verbose_name': 'Key Performance Indicator'},
        ),
        migrations.AlterField(
            model_name='beamline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beamlines', to='kpis.Department'),
        ),
    ]
