# Generated by Django 3.0.7 on 2020-06-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_auto_20200611_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Bar Chart'), (1, 'Line Graph'), (2, 'Scatter Plot')], default=0),
        ),
        migrations.AlterField(
            model_name='kpientry',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kpis.Beamline'),
        ),
        migrations.AlterField(
            model_name='kpientry',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='kpis.KPI'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='kpis.KPICategory'),
        ),
    ]
