# Generated by Django 3.0.7 on 2020-06-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_auto_20200612_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
