# Generated by Django 3.0.7 on 2020-06-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0004_auto_20200612_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpicategory',
            options={'verbose_name': 'KPI Category', 'verbose_name_plural': 'KPI Categories'},
        ),
        migrations.AlterModelOptions(
            name='kpientry',
            options={'verbose_name': 'KPI Entry', 'verbose_name_plural': 'KPI Entries'},
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
