# Generated by Django 3.0.7 on 2020-06-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0005_auto_20200612_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpientry',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kpientry',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
