# Generated by Django 3.0.7 on 2020-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0006_auto_20200612_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpientry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpientry',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
