# Generated by Django 3.0.7 on 2020-06-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0007_auto_20200612_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpientry',
            unique_together={('beamline', 'month')},
        ),
    ]
