# Generated by Django 3.0.7 on 2020-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0008_auto_20200614_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpientry',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
