# Generated by Django 3.0.7 on 2020-06-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0009_auto_20200614_0704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpientry',
            unique_together={('kpi', 'beamline', 'month')},
        ),
    ]
