# Generated by Django 3.0.7 on 2020-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0010_auto_20200614_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Average'), (1, 'Total'), (2, 'Text Only')], default=1),
        ),
    ]
