# Generated by Django 3.0.7 on 2020-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0011_auto_20200614_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
