# Generated by Django 3.0.7 on 2020-06-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0012_auto_20200615_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['category__priority', 'priority'], 'verbose_name': 'Key Performance Indicator'},
        ),
        migrations.AlterModelOptions(
            name='kpicategory',
            options={'ordering': ['priority'], 'verbose_name': 'KPI Category', 'verbose_name_plural': 'KPI Categories'},
        ),
    ]
