# Generated by Django 3.0.7 on 2020-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0014_beamline_beamlines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpicategory',
            options={'ordering': ['priority'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='description',
            field=models.CharField(blank=True, max_length=600, verbose_name='Strategic Goal'),
        ),
    ]
