# Generated by Django 3.0.7 on 2020-06-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0016_manager_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='kpis.Department'),
        ),
    ]
