# Generated by Django 3.0.7 on 2020-06-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0017_department_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='kpis.Department'),
        ),
    ]
