# Generated by Django 3.0.7 on 2020-07-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0018_kpi_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='beamline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='kpis.Beamline'),
        ),
    ]
