# Generated by Django 3.0.7 on 2020-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0022_kpi_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='beamlines',
            new_name='acronyms',
        ),
        migrations.AddField(
            model_name='unit',
            name='admin_roles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
