# Generated by Django 3.0.7 on 2020-08-24 20:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0023_auto_20200824_1429'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
