# Generated by Django 3.0.7 on 2020-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0024_auto_20200824_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='acronyms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='USO Acronyms'),
        ),
    ]
