# Generated by Django 3.0.7 on 2020-08-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0025_auto_20200824_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpientry',
            old_name='beamline',
            new_name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='kpientry',
            unique_together={('kpi', 'unit', 'month')},
        ),
    ]
