# Generated by Django 3.0.7 on 2020-08-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0026_auto_20200824_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='beamline',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='department',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
