# Generated by Django 3.0.7 on 2020-08-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0027_auto_20200824_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='admin_roles',
        ),
    ]
