# Generated by Django 3.0.7 on 2020-08-25 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0028_remove_unit_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='admin_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
