# Generated by Django 3.0.7 on 2020-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0030_auto_20200825_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='reporter',
            field=models.BooleanField(default=True),
        ),
    ]
