# Generated by Django 3.0.7 on 2020-08-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0031_unittype_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kind', models.IntegerField(choices=[(0, 'Related'), (1, 'Cumulative')], default=0)),
                ('kpis', models.ManyToManyField(to='kpis.KPI')),
            ],
        ),
    ]
